apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"cpu-perf-test:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"cpu-perf-test\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-01-07T16:25:08Z"
  generation: 10
  labels:
    app: cpu-perf-test
    app.kubernetes.io/component: cpu-perf-test
    app.kubernetes.io/instance: cpu-perf-test
  name: cpu-perf-test
  namespace: cpu-test
  resourceVersion: "2374838"
  uid: 3bb29be2-5003-406d-9c33-362ce65997ad
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: cpu-perf-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: cpu-perf-test
    spec:
      containers:
      - env:
        - name: PROCESSES_NUM
          value: "1"
        image: image-registry.openshift-image-registry.svc:5000/cpu-test/cpu-perf-test@sha256:87813d5d3fda47c10355507f3ebfc6f2fffe81e1d7cc0691b9b0621d88c4a317
        imagePullPolicy: IfNotPresent
        name: cpu-perf-test
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "32"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: ocp-edge117
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-01-07T16:25:42Z"
    lastUpdateTime: "2024-01-07T16:25:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-07T16:25:08Z"
    lastUpdateTime: "2024-01-07T18:30:11Z"
    message: ReplicaSet "cpu-perf-test-748d94f765" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
