apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"offender:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"offender\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-01-07T16:25:45Z"
  generation: 16
  labels:
    app: offender
    app.kubernetes.io/component: offender
    app.kubernetes.io/instance: offender
  name: offender
  namespace: cpu-test
  resourceVersion: "2424157"
  uid: 8693b86f-8325-46c9-a4ba-e460c67c6a7d
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: offender
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: offender
    spec:
      containers:
      - env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: OMP_NUM_THREADS
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        image: image-registry.openshift-image-registry.svc:5000/cpu-test/offender@sha256:43755f79f614752c87f7ef88d5f016908ece3cca44598f9720bb47f799319ba5
        imagePullPolicy: IfNotPresent
        name: offender
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: ocp-edge117
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-01-07T16:25:45Z"
    lastUpdateTime: "2024-01-07T18:02:23Z"
    message: ReplicaSet "offender-569968dccd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-01-08T10:30:22Z"
    lastUpdateTime: "2024-01-08T10:30:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
