apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"cpu-perf-test-one-thread:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"cpu-perf-test-one-thread\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-01-07T16:25:26Z"
  generation: 6
  labels:
    app: cpu-perf-test-one-thread
    app.kubernetes.io/component: cpu-perf-test-one-thread
    app.kubernetes.io/instance: cpu-perf-test-one-thread
  name: cpu-perf-test-one-thread
  namespace: cpu-test
  resourceVersion: "2402572"
  uid: f4570a68-1f64-4530-92ed-3b41837f881f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: cpu-perf-test-one-thread
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: cpu-perf-test-one-thread
    spec:
      containers:
      - args:
        - app.py
        command:
        - python3
        image: image-registry.openshift-image-registry.svc:5000/cpu-test/cpu-perf-test-one-thread@sha256:421afe0f654cd7162100775884ded6d44e56f901f5bd5a34d5c4580ffeca16d7
        imagePullPolicy: IfNotPresent
        name: cpu-perf-test-one-thread
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 4100m
            memory: 1Gi
          requests:
            cpu: 4100m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: ocp-edge117
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-08T09:33:16Z"
    lastUpdateTime: "2024-01-08T09:33:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-07T16:25:26Z"
    lastUpdateTime: "2024-01-08T10:11:44Z"
    message: ReplicaSet "cpu-perf-test-one-thread-59fc779c8b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
